#--------------------------------------------------------------------------
# Algorithm's library makefile.
#
# Created on: 2013-03-24
# Author: Abdullah Gharaibeh
#--------------------------------------------------------------------------
TARGET  = alg
ROOTDIR = ..
include $(ROOTDIR)/make.defs

DEPS := $(DEPS) $(TOTEM_DEPS)
INC  := $(INC) -I$(TOTEM_PATH)

all: lib

include $(ROOTDIR)/make.rules
