#--------------------------------------------------------------------------
# Totem library makefile.
#
# Created on: 2011-02-28
# Author: Abdullah Gharaibeh
#--------------------------------------------------------------------------
TARGET  = totem
ROOTDIR = ..
include $(ROOTDIR)/make.defs

all: lib

include $(ROOTDIR)/make.rules
